"""
Waypoint Follower for HW4

Adapts HW2's waypoint following logic with A*-generated waypoints.
Implements robot control using proportional guidance laws.
"""

import math
import time
import csv
import os
from typing import List, Tuple, Optional

import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32MultiArray
from geometry_msgs.msg import PoseStamped
from tf_transformations import euler_from_quaternion

from . import hw4_config as cfg


Waypoint = Tuple[float, float, float]  # (x, y, yaw)


def angdiff(a: float, b: float) -> float:
    """
    Compute signed angle difference from b to a, wrapped to [-pi, pi].

    Args:
        a: Target angle (radians)
        b: Current angle (radians)

    Returns:
        Signed angle difference (radians)
    """
    d = (a - b + math.pi) % (2 * math.pi) - math.pi
    return d


def passed_segment(
    px: float, py: float, gx: float, gy: float, x: float, y: float
) -> bool:
    """
    Check if robot has passed a waypoint segment.

    Args:
        px, py: Previous waypoint position
        gx, gy: Goal waypoint position
        x, y: Current robot position

    Returns:
        True if robot has passed the goal waypoint
    """
    ux, uy = (gx - px), (gy - py)
    seg2 = ux * ux + uy * uy
    if seg2 < 1e-6:
        return False
    sx, sy = (x - px), (y - py)
    s = (sx * ux + sy * uy) / seg2  # 0 at P, 1 at G
    return s > 1.05  # tiny cushion beyond goal


class WaypointFollowerHW4(Node):
    """
    Robot control node that follows waypoints generated by A* planner.

    Implements state machine with tracking, coasting, and search modes
    for robustness when pose estimation fails.
    """

    def __init__(self, waypoints: Optional[List[Waypoint]] = None):
        """
        Initialize waypoint follower.

        Args:
            waypoints: List of (x, y, yaw) tuples to follow.
                      If None, uses defaults from config.
        """
        super().__init__("hw4_waypoint_follower")

        # Waypoints to follow (can be set from A* planner)
        self.waypoints = waypoints or [
            cfg.DEFAULT_START,
            cfg.DEFAULT_GOAL,
        ]

        self.wpt_i = 0  # Current waypoint index
        self.pose = None  # Current estimated pose (PoseStamped)
        self.pose_time = 0.0  # Timestamp of last pose

        # State machine
        self.state = "TRACKING"
        self.state_enter_t = time.time()
        self.had_pose_recently = False
        self.hold_started = None
        self.search_dir = 1.0

        # Publishers and subscribers
        self.pub = self.create_publisher(Float32MultiArray, "motor_commands", 10)
        self.sub = self.create_subscription(
            PoseStamped, "/pose_estimated", self.on_pose, 10
        )
        self.timer = self.create_timer(cfg.TIMER_PERIOD_S, self.tick)

        # Logging
        self.log_path = os.path.expanduser("~/hw4_log.csv")
        self.logf = open(self.log_path, "w", newline="")
        self.w = csv.writer(self.logf)
        self.w.writerow(
            [
                "t",
                "state",
                "x",
                "y",
                "yaw",
                "gx",
                "gy",
                "gyaw",
                "rho",
                "eyaw",
                "L",
                "R",
            ]
        )

        self.get_logger().info(
            f"WaypointFollowerHW4 initialized with {len(self.waypoints)} waypoints"
        )

    def set_waypoints(self, waypoints: List[Waypoint]):
        """
        Update waypoint list (called by planner).

        Args:
            waypoints: List of (x, y, yaw) tuples
        """
        self.waypoints = waypoints
        self.wpt_i = 0
        self.get_logger().info(f"Waypoints updated: {len(waypoints)} points")

    def on_pose(self, msg: PoseStamped):
        """Callback for pose estimation updates."""
        self.pose = msg
        self.pose_time = time.time()

    def send_motor(self, L: float, R: float):
        """
        Send motor commands to robot.

        Args:
            L: Left motor velocity (m/s)
            R: Right motor velocity (m/s)
        """
        msg = Float32MultiArray()
        msg.data = [float(L), float(R)]
        self.pub.publish(msg)

    def stop(self):
        """Stop the robot by sending zero motor commands."""
        self.send_motor(0.0, 0.0)

    def state_now(self) -> float:
        """Get elapsed time in current state (seconds)."""
        return time.time() - self.state_enter_t

    def enter(self, new_state: str):
        """
        Transition to a new state.

        Args:
            new_state: Name of new state
        """
        self.state = new_state
        self.state_enter_t = time.time()

        # Reset state helpers
        if new_state == "SEARCH":
            self.had_pose_recently = False
            self.hold_started = None
            self.search_dir = 1.0

    def compute_tracking_cmd(
        self, x: float, y: float, yaw: float, gx: float, gy: float, gyaw: float
    ) -> Tuple[float, float, float, float, bool]:
        """
        Compute motor commands to track waypoint.

        Uses proportional guidance law:
        - Distance error -> linear velocity
        - Heading error -> angular velocity

        Args:
            x, y, yaw: Current pose
            gx, gy, gyaw: Goal pose

        Returns:
            (L, R, rho, e_yaw, done) where:
            - L, R: left/right motor velocities
            - rho: distance to goal
            - e_yaw: heading error
            - done: True if goal reached
        """
        dx, dy = gx - x, gy - y
        rho = math.hypot(dx, dy)
        goal_bearing = math.atan2(dy, dx)
        e_yaw_to_goal = angdiff(goal_bearing, yaw)

        # Proportional control
        v = cfg.Kv * rho
        w = cfg.Kw * e_yaw_to_goal
        v = max(-cfg.MAX_V, min(cfg.MAX_V, v))
        w = max(-cfg.MAX_W, min(cfg.MAX_W, w))

        # Convert to wheel velocities (differential drive)
        vL = v - 0.5 * w * cfg.BASELINE
        vR = v + 0.5 * w * cfg.BASELINE
        L = cfg.K_WHEEL * vL
        R = cfg.K_WHEEL * vR

        # Final heading alignment at goal
        if rho < cfg.POS_TOL:
            eh = angdiff(gyaw, yaw)
            w_close = max(-cfg.MAX_W, min(cfg.MAX_W, cfg.Kw * eh))
            vL = -0.5 * cfg.BASELINE * w_close
            vR = +0.5 * cfg.BASELINE * w_close
            L, R = cfg.K_WHEEL * vL, cfg.K_WHEEL * vR
            done_here = abs(eh) < cfg.YAW_TOL
            return L, R, rho, e_yaw_to_goal, done_here

        return L, R, rho, e_yaw_to_goal, False

    def log_row(
        self,
        state: str,
        x: float,
        y: float,
        yaw: float,
        gx: float,
        gy: float,
        gyaw: float,
        rho: float,
        eyaw: float,
        L: float,
        R: float,
    ):
        """Log control state to CSV."""
        t = self.get_clock().now().nanoseconds * 1e-9
        self.w.writerow([t, state, x, y, yaw, gx, gy, gyaw, rho, eyaw, L, R])

    def tick(self):
        """Main control loop (called at TIMER_PERIOD_S)."""
        now = time.time()
        pose_fresh = (self.pose is not None) and (
            (now - self.pose_time) < cfg.POSE_STALE_S
        )

        # Default log placeholders
        x = y = yaw = gx = gy = gyaw = rho = eyaw = L = R = 0.0

        # State machine
        if self.state == "TRACKING":
            if not pose_fresh:
                self.stop()
                self.enter("COAST")
            else:
                # Extract pose
                x = self.pose.pose.position.x
                y = self.pose.pose.position.y
                q = self.pose.pose.orientation
                (_, _, yaw) = euler_from_quaternion([q.x, q.y, q.z, q.w])

                gx, gy, gyaw = self.waypoints[self.wpt_i]

                L, R, rho, eyaw, done_here = self.compute_tracking_cmd(
                    x, y, yaw, gx, gy, gyaw
                )

                if done_here:
                    self.stop()
                    self.get_logger().info(
                        f"Reached waypoint {self.wpt_i}: ({gx:.2f},{gy:.2f},{gyaw:.2f})"
                    )
                    self.wpt_i = min(self.wpt_i + 1, len(self.waypoints) - 1)
                    time.sleep(0.4)
                else:
                    self.send_motor(L, R)

        elif self.state == "COAST":
            self.stop()
            if pose_fresh:
                self.enter("TRACKING")
            elif self.state_now() >= cfg.COAST_TIME_S:
                # Start rotating search
                self.send_motor(
                    -0.5 * cfg.BASELINE * cfg.SEARCH_OMEGA,
                    +0.5 * cfg.BASELINE * cfg.SEARCH_OMEGA,
                )
                self.enter("SEARCH")

        elif self.state == "SEARCH":
            elapsed = self.state_now()

            if pose_fresh:
                if not self.had_pose_recently:
                    self.had_pose_recently = True
                    self.hold_started = now
                elif (now - self.hold_started) >= cfg.REACQUIRE_HOLD_S:
                    self.had_pose_recently = False
                    self.enter("TRACKING")
            else:
                self.had_pose_recently = False

            # Flip search direction midway
            if elapsed > cfg.MAX_SEARCH_TIME_S / 2 and self.search_dir > 0:
                self.search_dir = -1.0

            omega = self.search_dir * cfg.SEARCH_OMEGA
            L = -0.5 * cfg.BASELINE * omega
            R = +0.5 * cfg.BASELINE * omega
            self.send_motor(L, R)

            if elapsed > cfg.MAX_SEARCH_TIME_S:
                self.stop()
                self.enter("FAILSAFE")

        elif self.state == "FAILSAFE":
            self.stop()
            if pose_fresh:
                self.enter("TRACKING")

        # Logging
        if self.pose is not None:
            x = self.pose.pose.position.x
            y = self.pose.pose.position.y
            q = self.pose.pose.orientation
            (_, _, yaw) = euler_from_quaternion([q.x, q.y, q.z, q.w])

        if self.wpt_i < len(self.waypoints):
            gx, gy, gyaw = self.waypoints[self.wpt_i]
        else:
            gx, gy, gyaw = self.waypoints[-1]

        self.log_row(self.state, x, y, yaw, gx, gy, gyaw, rho, eyaw, L, R)

    def destroy_node(self):
        """Cleanup on shutdown."""
        try:
            self.stop()
            self.logf.close()
        finally:
            super().destroy_node()


def main():
    rclpy.init()
    node = WaypointFollowerHW4()
    rclpy.spin(node)
    rclpy.shutdown()


if __name__ == "__main__":
    main()
