apriltags:
  - id: 0
    # Position in map frame (meters)
    x: 1.2573
    y: -0.6223
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5

  - id: 1
    # Position in map frame (meters)
    x: 1.2573
    y: 0.4572
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5

  - id: 2
    # Position in map frame (meters)
    x: 0.5969
    y: -1.1938
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.0
    qy: 0.707
    qz: 0.707
    qw: 0.0

  - id: 3
    # Position in map frame (meters)
    x: -0.8509
    y: -1.2192
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.0
    qy: 0.707
    qz: 0.707
    qw: 0.0

  - id: 4
    # Position in map frame (meters)
    x: 0.6223
    y: 1.2573
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707

  - id: 5
    # Position in map frame (meters)
    x: -0.6604
    y: 1.2573
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707

  - id: 6
    # Position in map frame (meters)
    x: -1.9177
    y: 0.5588
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5

  - id: 7
    # Position in map frame (meters)
    x: -1.9177
    y: -0.5334
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5

  - id: 8
    # Position in map frame (meters)
    x: -1.9177
    y: -0.0254
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5

  - id: 9
    # Position in map frame (meters)
    x: 1.2573
    y: -0.1143
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5

  - id: 10
    # Position in map frame (meters)
    x: -0.2159
    y: -1.1938
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.0
    qy: 0.707
    qz: 0.707
    qw: 0.0

  - id: 11
    # Position in map frame (meters)
    x: -0.0508
    y: 1.2573
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707
