apriltags:
  - id: 0
    # Position in map frame (meters)
    x: 2.159
    y: 1.6
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5

  - id: 1
    # Position in map frame (meters)
    x: 2.134
    y: -0.178
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5

  - id: 2
    # Position in map frame (meters)
    x: 1.549
    y: -0.406
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.0
    qy: 0.707
    qz: 0.707
    qw: 0.0

  - id: 3
    # Position in map frame (meters)
    x: 0.229
    y: -0.406
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.0
    qy: 0.707
    qz: 0.707
    qw: 0.0

  - id: 4
    # Position in map frame (meters)
    x: 1.321
    y: 1.994
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707

  - id: 5
    # Position in map frame (meters)
    x: 0.152
    y: 2.032
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707

  - id: 6
    # Position in map frame (meters)
    x: -0.406
    y: 1.651
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5

  - id: 7
    # Position in map frame (meters)
    x: -0.445
    y: -0.178
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5

  - id: 8
    # Position in map frame (meters)
    x: 0.762
    y: 0.673
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.707
    qy: 0.0
    qz: 0.0
    qw: 0.707

  - id: 9
    # Position in map frame (meters)
    x: 0.914
    y: 0.813
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: 0.5
    qz: 0.5
    qw: 0.5

  - id: 10
    # Position in map frame (meters)
    x: 0.762
    y: 0.965
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.0
    qy: 0.707
    qz: 0.707
    qw: 0.0

  - id: 11
    # Position in map frame (meters)
    x: 0.584
    y: 0.813
    z: 0.0
    # Orientation in map frame (quaternion)
    qx: 0.5
    qy: -0.5
    qz: -0.5
    qw: 0.5
